import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    alignItems: "center",
    marginLeft: 16,
  },
  answer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    paddingHorizontal: 16,
    minHeight: 50,
    paddingVertical: 8,
    borderRadius: 8,
    width: "100%",
    backgroundColor: "rgba(255, 255, 255, 0.4)",
  },
  correctAnswer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    paddingHorizontal: 16,
    minHeight: 50,
    paddingVertical: 8,
    borderRadius: 8,
    width: "100%",
    backgroundColor: "rgba(24, 240, 64, 0.4)",
    justifyContent: "space-between",
  },
  wrongAnswer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    paddingHorizontal: 16,
    minHeight: 50,
    paddingVertical: 8,
    borderRadius: 8,
    width: "100%",
    backgroundColor: "rgba(255, 0, 0, 0.4)",
    justifyContent: "space-between",
  },
  text: {
    width: "80%",
    fontSize: 16,
    fontWeight: "600",
    color: "#fff",
    textShadowColor: "black",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
});
